name: update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y
      - run: sudo apt install -y gettext jq httpie
      - run: sh ./update-template.sh
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update version'
